migration: ['db/migrate/*', 'db/schema.rb']
infrastructure: 'infrastrucure/**'
backend: [ 'app/models/**', 'app/controllers/**']
frontend: ['app/views/**']
ci: ['.github/**']
dependencies: ['Gemfile', 'package*']
