migration: 
  - any: ['db/migrate/*', 'db/schema.rb']
infrastructure: 
  - 'infrastrucure/**'
backend: 
  - any: [ 'app/models/**', 'app/controllers/**']
frontend: 
  - 'app/views/**'
ci: 
  - '.github/**'
dependencies: 
  - any: ['Gemfile', 'package*']
