repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    files: '.infrastructure/**'
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_docs
      # - id: terraform_tfsec
      # - id: terraform_checkov
