project: homelink

cluster: staging

image:
  ecr: homelink
  tag: "{{ .ImageTag }}"

task_defaults:
  cpu: 512
  memory: 2x

network:
  public_ip: false
  subnets:
    - subnet-083c8d5b2dda7328f
    - subnet-0e7dfee79a4b29462
    - subnet-07fd961a33c92ab45
  security_groups:
    - sg-0b1a2582c766e047c

services:
  - name: web
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    desired: 2
    load_balancer:
      port: 8080
      target_group: chainlink-staging-http
  - name: worker
    command: ["bundle", "exec", "shoryuken", "-R", "-C", "config/shoryuken.yml"]
    desired: 1
