concurrency: 25  # The number of allocated threads to process messages. Default 25
delay: 0         # The delay in seconds to pause empty queues. Default 0
queues:
  - homelink_<%= ENV['RAILS_ENV'] %>_main
  - homelink_<%= ENV['RAILS_ENV'] %>_high
